Repository powsybl/powsybl-afs, pull requests merged in 2020-07, with the labels that each got.

#42 Fix event parentchanged
  afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
  afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
  afs-storage-api/src/main/java/com/powsybl/afs/storage/events/ParentChanged.java
  afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
  afs-storage-api/src/test/java/com/powsybl/afs/storage/events/NodeEventTest.java
Labels: PR: ready-to-be-merged

#43 Add node ref id in tasks
  afs-core/src/main/java/com/powsybl/afs/LocalTaskMonitor.java
  afs-core/src/main/java/com/powsybl/afs/TaskMonitor.java
  afs-core/src/test/java/com/powsybl/afs/LocalTaskMonitorTest.java
Labels: PR: ready-to-be-merged

#47 Add missing dependency removed event on node deletion
  afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
  afs-mapdb-storage/src/main/java/com/powsybl/afs/mapdb/storage/MapDbAppStorage.java
  afs-storage-api/src/test/java/com/powsybl/afs/storage/AbstractAppStorageTest.java
Labels: PR: ready-to-be-merged

#48 Add more log for server actions
  afs-ws/afs-ws-server/src/main/java/com/powsybl/afs/ws/server/AppStorageServer.java
Labels: PR: ready-to-be-merged, PR: waiting-for-info-author

#49 archive keep result time series
  afs-core/src/main/java/com/powsybl/afs/AbstractNodeBase.java
  afs-core/src/main/java/com/powsybl/afs/AppFileSystemTool.java
  afs-core/src/main/java/com/powsybl/afs/ProjectFileExtension.java
  afs-core/src/test/java/com/powsybl/afs/AfsBaseTest.java
  afs-storage-api/src/main/java/com/powsybl/afs/storage/AppStorageArchive.java
Labels: PR: waiting-for-correction, PR: waiting-for-review
