Repository powsybl/powsybl-afs, pull requests merged in 2020-10, with the labels that each got.

#51 Remove node event connection (listener) when fetching dependencies
  afs-core/src/main/java/com/powsybl/afs/AppFileSystem.java
  afs-core/src/main/java/com/powsybl/afs/OrderedDependencyManager.java
  afs-core/src/main/java/com/powsybl/afs/Project.java
  afs-core/src/main/java/com/powsybl/afs/ProjectFile.java
  afs-core/src/main/java/com/powsybl/afs/ProjectFileCreationContext.java
Labels: PR: ready-to-be-merged

#55 Fix cassandra data node OutputStream potential overlap
  afs-cassandra/src/main/java/com/powsybl/afs/cassandra/CassandraAppStorage.java
  afs-cassandra/src/test/java/com/powsybl/afs/cassandra/CassandraDataSplitTest.java
Labels: PR: waiting-for-review, bug

#54 Add security context
  afs-ws/afs-ws-server-utils/pom.xml
  afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/AfsSimpleSecurityContext.java
  afs-ws/afs-ws-server-utils/src/main/java/com/powsybl/afs/ws/server/utils/JwtTokenNeededFilter.java
  afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/AfsSimpleSecurityContextTest.java
  afs-ws/afs-ws-server-utils/src/test/java/com/powsybl/afs/ws/server/utils/CodeCoverageTest.java
Labels: PR: waiting-for-review

#60 Update powsybl-core version to v3.3.2
  pom.xml
Labels: PR: waiting-for-review

#57 [AFS WS] AFS client : implement automatic reconnection to websocket endpoint
  afs-action-dsl/pom.xml
  afs-contingency/pom.xml
  afs-core/pom.xml
  afs-ext-base/pom.xml
  afs-local/pom.xml
  afs-mapdb-storage/pom.xml
  afs-mapdb/pom.xml
  afs-scripting/pom.xml
  afs-security-analysis-local/pom.xml
  afs-security-analysis/pom.xml
  afs-storage-api/pom.xml
  afs-storage-api/src/main/java/com/powsybl/afs/storage/EventsBus.java
  afs-ws/afs-ws-client-utils/pom.xml
  afs-ws/afs-ws-client-utils/src/main/java/com/powsybl/afs/ws/client/utils/RemoteServiceConfig.java
  afs-ws/afs-ws-client-utils/src/test/java/com/powsybl/afs/ws/client/utils/RemoteServiceConfigTest.java
  afs-ws/afs-ws-client/src/main/java/com/powsybl/afs/ws/client/RemoteAppFileSystemProvider.java
  afs-ws/afs-ws-server/pom.xml
  afs-ws/afs-ws-server/src/test/java/com/powsybl/afs/ws/server/AppStorageServerTest.java
  afs-ws/afs-ws-storage/pom.xml
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/NodeEventClient.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/RemoteAppStorage.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/WebSocketEventsBus.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/websocket/AutoReconnectionConnectionManager.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/websocket/StandardConnectionManager.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/websocket/WebsocketConnectionManager.java
  afs-ws/afs-ws-storage/src/main/java/com/powsybl/afs/ws/storage/websocket/WebsocketConnectionPolicy.java
  afs-ws/afs-ws-storage/src/test/java/com/powsybl/afs/ws/storage/NodeEventClientReconnectionTest.java
  afs-ws/afs-ws-storage/src/test/java/com/powsybl/afs/ws/storage/websocket/WebsocketConnectionPolicyTest.java
  pom.xml
Labels: PR: waiting-for-review
